[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  checkExternal = true
  skipPatterns = ["repo/dist", "dist/styles/public/images"]
  todoPatterns = [*]
